### ISSUE TITLE
Support .NET Standard 1.0+

### ISSUE THREAD

**Issue by goofballLogic** [blushingpenguin/Quill.Delta#1]
Would like to use this library from a legacy product that is only on .NET Framework 4.5 and therefore cannot consume .NET Standard >= 1.0.

It's hard to believe that this codebase needs features from .NET Standard 2.0?

**Comment by blushingpenguin** [comment]
.NET Standard 1.3 was the minimum version (~NET Framework 4.6), because earlier versions did not support System.Xml.XmlDocument.

Rather than modify the code to use XDocument, I have modified the package to target .NET Standard 1.3 and net40 instead, hopefully that should cover your use case.

**Comment by goofballLogic** [comment]
Thanks!

⁣Sent from BlueMail ​
